apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
spec:
  selector:
      matchLabels:
        app: todos-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: todos-api:1.0.0.SNAP
          imagePullPolicy: Never
          ports:
            - containerPort: 8080