spring:
  application:
    name: todos-api
logging:
  level:
    io.corbs: DEBUG
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /ops
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
todos:
  api:
    limit: 16
#todos.api.limit=16